version: '3.7'

services:
  gallery:
    restart: always
    image: genamoscow/gallery
    container_name: "gallery"
    init: true
    depends_on:
      - postgresql
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresql/postgres
    ports:
      - 8081:8080


  postgresql:
    restart: always
    image: postgres:11.2
    container_name: "postgresql"
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - 8001:5432
